"""empty message

Revision ID: 4b38d0e0a585
Revises: f1bbc3b0a2c9
Create Date: 2020-12-05 20:20:20.142665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b38d0e0a585'
down_revision = 'f1bbc3b0a2c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('health_providers_title_id_fkey', 'health_providers', type_='foreignkey')
    op.create_foreign_key(None, 'health_providers', 'states', ['title_id'], ['id'])
    op.drop_constraint('users_relationship_preference_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'relationship_preference_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('relationship_preference_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_relationship_preference_id_fkey', 'users', 'relationship_preference', ['relationship_preference_id'], ['id'])
    op.drop_constraint(None, 'health_providers', type_='foreignkey')
    op.create_foreign_key('health_providers_title_id_fkey', 'health_providers', 'tags', ['title_id'], ['id'])
    # ### end Alembic commands ###
