"""empty message

Revision ID: 4d50de09aafd
Revises: 2986ecde9e69
Create Date: 2020-12-05 20:04:16.942022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d50de09aafd'
down_revision = '2986ecde9e69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sexuality',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sexuality', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sexuality')
    # ### end Alembic commands ###
