"""empty message

Revision ID: 82163d2c2b41
Revises: acc92f75c273
Create Date: 2020-12-05 18:48:45.855617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82163d2c2b41'
down_revision = 'acc92f75c273'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('specialties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('specialty', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provider_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['health_providers.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provider_specialties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('specialty_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['health_providers.id'], ),
    sa.ForeignKeyConstraint(['specialty_id'], ['specialties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user_providers', sa.Column('health_provider_id', sa.Integer(), nullable=False))
    op.add_column('user_providers', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'user_providers', 'health_providers', ['health_provider_id'], ['id'])
    op.create_foreign_key(None, 'user_providers', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_providers', type_='foreignkey')
    op.drop_constraint(None, 'user_providers', type_='foreignkey')
    op.drop_column('user_providers', 'user_id')
    op.drop_column('user_providers', 'health_provider_id')
    op.drop_table('provider_specialties')
    op.drop_table('provider_services')
    op.drop_table('specialties')
    op.drop_table('services')
    # ### end Alembic commands ###
