"""empty message

Revision ID: 82ee06e5ffb7
Revises: 82163d2c2b41
Create Date: 2020-12-05 19:01:13.112752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82ee06e5ffb7'
down_revision = '82163d2c2b41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('state')
    )
    op.create_table('states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('state')
    )
    op.create_table('zip_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('state')
    )
    op.add_column('health_providers', sa.Column('city_id', sa.Integer(), nullable=False))
    op.add_column('health_providers', sa.Column('state_id', sa.Integer(), nullable=False))
    op.add_column('health_providers', sa.Column('zip_code_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'health_providers', 'cities', ['city_id'], ['id'])
    op.create_foreign_key(None, 'health_providers', 'zip_codes', ['zip_code_id'], ['id'])
    op.create_foreign_key(None, 'health_providers', 'states', ['state_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'health_providers', type_='foreignkey')
    op.drop_constraint(None, 'health_providers', type_='foreignkey')
    op.drop_constraint(None, 'health_providers', type_='foreignkey')
    op.drop_column('health_providers', 'zip_code_id')
    op.drop_column('health_providers', 'state_id')
    op.drop_column('health_providers', 'city_id')
    op.drop_table('zip_codes')
    op.drop_table('states')
    op.drop_table('cities')
    # ### end Alembic commands ###
