"""empty message

Revision ID: acc92f75c273
Revises: 6484736ede02
Create Date: 2020-12-05 18:12:03.264458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acc92f75c273'
down_revision = '6484736ede02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_title',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word')
    )
    op.create_table('user_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('health_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=40), nullable=False),
    sa.Column('last_name', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['title_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('health_provider_id', sa.Integer(), nullable=False),
    sa.Column('good', sa.Text(), nullable=True),
    sa.Column('bad', sa.Text(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['health_provider_id'], ['health_providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quality', sa.Boolean(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_tags')
    op.drop_table('reviews')
    op.drop_table('health_providers')
    op.drop_table('user_providers')
    op.drop_table('tags')
    op.drop_table('health_title')
    # ### end Alembic commands ###
