"""empty message

Revision ID: d8e593bbcc35
Revises: 4b38d0e0a585
Create Date: 2020-12-05 20:20:46.318249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8e593bbcc35'
down_revision = '4b38d0e0a585'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('health_providers_title_id_fkey', 'health_providers', type_='foreignkey')
    op.create_foreign_key(None, 'health_providers', 'health_title', ['title_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'health_providers', type_='foreignkey')
    op.create_foreign_key('health_providers_title_id_fkey', 'health_providers', 'states', ['title_id'], ['id'])
    # ### end Alembic commands ###
