"""empty message

Revision ID: f1bbc3b0a2c9
Revises: 8a52b49d563f
Create Date: 2020-12-05 20:07:37.883736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1bbc3b0a2c9'
down_revision = '8a52b49d563f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sexuality_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'sexuality', ['sexuality_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'sexuality_id')
    # ### end Alembic commands ###
